const REG='Registrations',SET='EventSettings';
const VALID={Brampton:['2026-10-10','2026-10-24'],Halifax:['2026-10-17','2026-10-18']};
const HEAD=['Registration ID','Timestamp','Full Name','Address','City','Province','Phone','Email','Status in Canada','Status Expiry Date','Event Location','Event Date','Preferred Arrival Time','Applicant Query','Consent','Lead Source','UTM Source','UTM Medium','UTM Campaign','UTM Content','UTM Term','Attendance Status','Consultant','Follow-up Required','Follow-up Date','Staff Notes'];
function out(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function c(v,n){return String(v==null?'':v).replace(/[<>]/g,'').trim().slice(0,n||500)}
function normDate(v){if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v;return Utilities.formatDate(new Date(v),Session.getScriptTimeZone(),'yyyy-MM-dd')}
function normTime(v){if(/^\d{2}:\d{2}$/.test(v))return v;let d=new Date('2000/01/01 '+v);return isNaN(d)?'':Utilities.formatDate(d,Session.getScriptTimeZone(),'HH:mm')}
function events(){let s=SpreadsheetApp.getActive().getSheetByName(SET);if(!s)throw Error('EventSettings missing');return s.getDataRange().getDisplayValues().slice(1).filter(r=>String(r[6]).toUpperCase()==='TRUE').map(r=>({location:r[0],date:normDate(r[1]),displayDate:r[2],startTime:normTime(r[3]),endTime:normTime(r[4]),intervalMinutes:Number(r[5])||30})).filter(x=>VALID[x.location]&&VALID[x.location].includes(x.date))}
function slots(a,b,step){let A=a.split(':').map(Number),B=b.split(':').map(Number),n=A[0]*60+A[1],z=B[0]*60+B[1],o=[];for(;n<z;n+=step){let h=Math.floor(n/60),m=n%60;o.push((h%12||12)+':'+String(m).padStart(2,'0')+' '+(h>=12?'PM':'AM'))}return o}
function doGet(e){return (e.parameter.action||'')==='events'?out({success:true,events:events()}):out({success:false,message:'Unknown action'})}
function doPost(e){try{let d=JSON.parse(e.postData.contents||'{}');if(c(d.website,100))return out({success:false,code:'SPAM',message:'Registration could not be completed.'});for(let k of ['fullName','address','city','province','phone','email','status','expiryDate','location','date','arrivalTime'])if(!c(d[k]))return out({success:false,code:'VALIDATION',message:'Please complete all required fields.'});let loc=c(d.location,20),date=c(d.date,10),time=c(d.arrivalTime,20);if(!VALID[loc]||!VALID[loc].includes(date))return out({success:false,code:'EVENT_INVALID',message:'Please select a valid Open House date.'});let ev=events().find(x=>x.location===loc&&x.date===date);if(!ev||!ev.startTime||!ev.endTime)return out({success:false,code:'EVENT_NOT_CONFIGURED',message:'This event time is not available for registration yet.'});if(!slots(ev.startTime,ev.endTime,ev.intervalMinutes).includes(time))return out({success:false,code:'TIME_INVALID',message:'Please select a valid preferred arrival time.'});if(!/^\+?[0-9 ()-]{7,20}$/.test(c(d.phone,30))||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(c(d.email,150)))return out({success:false,code:'VALIDATION',message:'Please check your phone number and email address.'});if(d.consent!==true)return out({success:false,code:'CONSENT',message:'Please accept the consent statement.'});let lock=LockService.getScriptLock();lock.waitLock(20000);try{let sh=SpreadsheetApp.getActive().getSheetByName(REG),v=sh.getDataRange().getDisplayValues(),email=c(d.email,150).toLowerCase(),phone=c(d.phone,30).replace(/\D/g,'');for(let i=1;i<v.length;i++)if(v[i][11]===date&&(v[i][7].toLowerCase()===email||v[i][6].replace(/\D/g,'')===phone))return out({success:false,code:'DUPLICATE',message:"It looks like you're already registered for this Open House."});let id='SR-OH-2026-'+String(v.length).padStart(4,'0'),src=c(d.leadSource,80)||({qr:'QR Code',instagram:'Instagram',facebook:'Facebook',tiktok:'TikTok',whatsapp:'WhatsApp'}[c(d.utmSource,100).toLowerCase()]||'Direct');sh.appendRow([id,new Date(),c(d.fullName,120),c(d.address,200),c(d.city,100),c(d.province,60),c(d.phone,30),c(d.email,150),c(d.status,60),c(d.expiryDate,10),loc,date,time,c(d.query,500),'Yes',src,c(d.utmSource,100),c(d.utmMedium,100),c(d.utmCampaign,150),c(d.utmContent,150),c(d.utmTerm,150),'Registered','','No','','']);return out({success:true,registrationId:id})}finally{lock.releaseLock()}}catch(err){console.error(err);return out({success:false,code:'SERVER_ERROR',message:'Registration could not be completed. Please try again.'})}}
function setupSheets(){let ss=SpreadsheetApp.getActive(),r=ss.getSheetByName(REG)||ss.insertSheet(REG),s=ss.getSheetByName(SET)||ss.insertSheet(SET);r.clear();r.getRange(1,1,1,HEAD.length).setValues([HEAD]).setFontWeight('bold').setBackground('#073b3a').setFontColor('#fff');r.setFrozenRows(1);s.clear();s.getRange(1,1,5,7).setValues([['Location','Date','Display Date','Start Time','End Time','Interval Minutes','Active'],['Brampton','2026-10-10','October 10, 2026','','',30,true],['Brampton','2026-10-24','October 24, 2026','','',30,true],['Halifax','2026-10-17','October 17, 2026','','',30,true],['Halifax','2026-10-18','October 18, 2026','','',30,true]]);s.getRange(1,1,1,7).setFontWeight('bold').setBackground('#073b3a').setFontColor('#fff');s.setFrozenRows(1);r.getRange('V2:V').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Registered','Confirmed','Attended','No Show','Cancelled'],true).build());r.getRange('X2:X').setDataValidation(SpreadsheetApp.newDataValidation().requireValueInList(['Yes','No'],true).build());s.getRange('G2:G5').insertCheckboxes().setValue(true);r.autoResizeColumns(1,26);s.autoResizeColumns(1,7)}
